# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from poodle_async_full.models.core_reportbuilder_conditions_add_response_availableconditions_inner import CoreReportbuilderConditionsAddResponseAvailableconditionsInner
from poodle_async_full.models.core_reportbuilder_filters_add_response_activefilters_inner import CoreReportbuilderFiltersAddResponseActivefiltersInner
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreReportbuilderFiltersReorderResponse(BaseModel):
    """
    CoreReportbuilderFiltersReorderResponse
    """ # noqa: E501
    activefilters: List[CoreReportbuilderFiltersAddResponseActivefiltersInner] = Field(description="activefilters")
    availablefilters: List[CoreReportbuilderConditionsAddResponseAvailableconditionsInner] = Field(description="availablefilters")
    hasactivefilters: StrictBool = Field(description="hasactivefilters")
    hasavailablefilters: StrictBool = Field(description="hasavailablefilters")
    helpicon: StrictStr = Field(description="helpicon")
    __properties: ClassVar[List[str]] = ["activefilters", "availablefilters", "hasactivefilters", "hasavailablefilters", "helpicon"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreReportbuilderFiltersReorderResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in activefilters (list)
        _items = []
        if self.activefilters:
            for _item_activefilters in self.activefilters:
                if _item_activefilters:
                    _items.append(_item_activefilters.to_dict())
            _dict['activefilters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in availablefilters (list)
        _items = []
        if self.availablefilters:
            for _item_availablefilters in self.availablefilters:
                if _item_availablefilters:
                    _items.append(_item_availablefilters.to_dict())
            _dict['availablefilters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreReportbuilderFiltersReorderResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreReportbuilderFiltersReorderResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "activefilters": [CoreReportbuilderFiltersAddResponseActivefiltersInner.from_dict(_item) for _item in obj["activefilters"]] if obj.get("activefilters") is not None else None,
            "availablefilters": [CoreReportbuilderConditionsAddResponseAvailableconditionsInner.from_dict(_item) for _item in obj["availablefilters"]] if obj.get("availablefilters") is not None else None,
            "hasactivefilters": obj.get("hasactivefilters") if obj.get("hasactivefilters") is not None else False,
            "hasavailablefilters": obj.get("hasavailablefilters") if obj.get("hasavailablefilters") is not None else False,
            "helpicon": obj.get("helpicon") if obj.get("helpicon") is not None else ''
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


