# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreMessageGetMessageProcessorResponse(BaseModel):
    """
    CoreMessageGetMessageProcessorResponse
    """ # noqa: E501
    systemconfigured: Optional[StrictBool] = Field(description="Site configuration status")
    userconfigured: Optional[StrictBool] = Field(description="The user configuration status")
    __properties: ClassVar[List[str]] = ["systemconfigured", "userconfigured"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreMessageGetMessageProcessorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if systemconfigured (nullable) is None
        # and model_fields_set contains the field
        if self.systemconfigured is None and "systemconfigured" in self.model_fields_set:
            _dict['systemconfigured'] = None

        # set to None if userconfigured (nullable) is None
        # and model_fields_set contains the field
        if self.userconfigured is None and "userconfigured" in self.model_fields_set:
            _dict['userconfigured'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreMessageGetMessageProcessorResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreMessageGetMessageProcessorResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "systemconfigured": obj.get("systemconfigured"),
            "userconfigured": obj.get("userconfigured")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


