# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreCalendarGetCalendarDayViewResponseDate(BaseModel):
    """
    CoreCalendarGetCalendarDayViewResponseDate
    """ # noqa: E501
    hours: StrictInt = Field(description="hours")
    mday: StrictInt = Field(description="mday")
    minutes: StrictInt = Field(description="minutes")
    mon: StrictInt = Field(description="mon")
    month: StrictStr = Field(description="month")
    seconds: StrictInt = Field(description="seconds")
    timestamp: StrictInt = Field(description="timestamp")
    wday: StrictInt = Field(description="wday")
    weekday: StrictStr = Field(description="weekday")
    yday: StrictInt = Field(description="yday")
    year: StrictInt = Field(description="year")
    __properties: ClassVar[List[str]] = ["hours", "mday", "minutes", "mon", "month", "seconds", "timestamp", "wday", "weekday", "yday", "year"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreCalendarGetCalendarDayViewResponseDate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreCalendarGetCalendarDayViewResponseDate from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreCalendarGetCalendarDayViewResponseDate" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "hours": obj.get("hours") if obj.get("hours") is not None else 0,
            "mday": obj.get("mday") if obj.get("mday") is not None else 0,
            "minutes": obj.get("minutes") if obj.get("minutes") is not None else 0,
            "mon": obj.get("mon") if obj.get("mon") is not None else 0,
            "month": obj.get("month") if obj.get("month") is not None else '',
            "seconds": obj.get("seconds") if obj.get("seconds") is not None else 0,
            "timestamp": obj.get("timestamp") if obj.get("timestamp") is not None else 0,
            "wday": obj.get("wday") if obj.get("wday") is not None else 0,
            "weekday": obj.get("weekday") if obj.get("weekday") is not None else '',
            "yday": obj.get("yday") if obj.get("yday") is not None else 0,
            "year": obj.get("year") if obj.get("year") is not None else 0
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


