# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreMessageGetUserMessagePreferencesResponsePreferencesComponentsInnerNotificationsInnerProcessorsInner(BaseModel):
    """
    CoreMessageGetUserMessagePreferencesResponsePreferencesComponentsInnerNotificationsInnerProcessorsInner
    """ # noqa: E501
    displayname: Optional[StrictStr] = Field(description="Display name")
    enabled: Optional[StrictBool] = Field(description="Is enabled?")
    locked: Optional[StrictBool] = Field(description="Is locked by admin?")
    lockedmessage: Optional[StrictStr] = Field(default=None, description="Text to display if locked")
    name: Optional[StrictStr] = Field(description="Processor name")
    userconfigured: Optional[StrictInt] = Field(description="Is configured?")
    __properties: ClassVar[List[str]] = ["displayname", "enabled", "locked", "lockedmessage", "name", "userconfigured"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreMessageGetUserMessagePreferencesResponsePreferencesComponentsInnerNotificationsInnerProcessorsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if displayname (nullable) is None
        # and model_fields_set contains the field
        if self.displayname is None and "displayname" in self.model_fields_set:
            _dict['displayname'] = None

        # set to None if enabled (nullable) is None
        # and model_fields_set contains the field
        if self.enabled is None and "enabled" in self.model_fields_set:
            _dict['enabled'] = None

        # set to None if locked (nullable) is None
        # and model_fields_set contains the field
        if self.locked is None and "locked" in self.model_fields_set:
            _dict['locked'] = None

        # set to None if lockedmessage (nullable) is None
        # and model_fields_set contains the field
        if self.lockedmessage is None and "lockedmessage" in self.model_fields_set:
            _dict['lockedmessage'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if userconfigured (nullable) is None
        # and model_fields_set contains the field
        if self.userconfigured is None and "userconfigured" in self.model_fields_set:
            _dict['userconfigured'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreMessageGetUserMessagePreferencesResponsePreferencesComponentsInnerNotificationsInnerProcessorsInner from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreMessageGetUserMessagePreferencesResponsePreferencesComponentsInnerNotificationsInnerProcessorsInner" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "displayname": obj.get("displayname"),
            "enabled": obj.get("enabled"),
            "locked": obj.get("locked"),
            "lockedmessage": obj.get("lockedmessage"),
            "name": obj.get("name"),
            "userconfigured": obj.get("userconfigured")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


