# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from poodle_async_full.models.auth_email_get_signup_settings_response_warnings_inner import AuthEmailGetSignupSettingsResponseWarningsInner
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreBlogGetAccessInformationResponse(BaseModel):
    """
    CoreBlogGetAccessInformationResponse
    """ # noqa: E501
    cancreate: Optional[StrictBool] = Field(description="Whether the user can create blog entries")
    canmanageentries: Optional[StrictBool] = Field(description="Whether the user can manage blog entries")
    canmanageexternal: Optional[StrictBool] = Field(description="Whether the user can manage external blogs")
    cansearch: Optional[StrictBool] = Field(description="Whether the user can search blogs")
    canview: Optional[StrictBool] = Field(description="Whether the user can view blogs")
    canviewdrafts: Optional[StrictBool] = Field(description="Whether the user can view drafts")
    warnings: Optional[List[AuthEmailGetSignupSettingsResponseWarningsInner]] = Field(default=None, description="list of warnings")
    __properties: ClassVar[List[str]] = ["cancreate", "canmanageentries", "canmanageexternal", "cansearch", "canview", "canviewdrafts", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreBlogGetAccessInformationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        # set to None if cancreate (nullable) is None
        # and model_fields_set contains the field
        if self.cancreate is None and "cancreate" in self.model_fields_set:
            _dict['cancreate'] = None

        # set to None if canmanageentries (nullable) is None
        # and model_fields_set contains the field
        if self.canmanageentries is None and "canmanageentries" in self.model_fields_set:
            _dict['canmanageentries'] = None

        # set to None if canmanageexternal (nullable) is None
        # and model_fields_set contains the field
        if self.canmanageexternal is None and "canmanageexternal" in self.model_fields_set:
            _dict['canmanageexternal'] = None

        # set to None if cansearch (nullable) is None
        # and model_fields_set contains the field
        if self.cansearch is None and "cansearch" in self.model_fields_set:
            _dict['cansearch'] = None

        # set to None if canview (nullable) is None
        # and model_fields_set contains the field
        if self.canview is None and "canview" in self.model_fields_set:
            _dict['canview'] = None

        # set to None if canviewdrafts (nullable) is None
        # and model_fields_set contains the field
        if self.canviewdrafts is None and "canviewdrafts" in self.model_fields_set:
            _dict['canviewdrafts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreBlogGetAccessInformationResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreBlogGetAccessInformationResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "cancreate": obj.get("cancreate"),
            "canmanageentries": obj.get("canmanageentries"),
            "canmanageexternal": obj.get("canmanageexternal"),
            "cansearch": obj.get("cansearch"),
            "canview": obj.get("canview"),
            "canviewdrafts": obj.get("canviewdrafts"),
            "warnings": [AuthEmailGetSignupSettingsResponseWarningsInner.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


