# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreGradingGetDefinitionsResponseAreasInnerDefinitionsInnerGuideGuideCriteriaInner(BaseModel):
    """
    CoreGradingGetDefinitionsResponseAreasInnerDefinitionsInnerGuideGuideCriteriaInner
    """ # noqa: E501
    description: Optional[StrictStr] = Field(default=None, description="description")
    descriptionformat: Optional[StrictInt] = Field(default=None, description="description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)")
    descriptionmarkers: Optional[StrictStr] = Field(default=None, description="markers description")
    descriptionmarkersformat: Optional[StrictInt] = Field(default=None, description="descriptionmarkers format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)")
    id: Optional[StrictInt] = Field(default=None, description="criterion id")
    maxscore: Optional[Union[StrictFloat, StrictInt]] = Field(description="maximum score")
    shortname: Optional[StrictStr] = Field(description="description")
    sortorder: Optional[StrictInt] = Field(default=None, description="sortorder")
    __properties: ClassVar[List[str]] = ["description", "descriptionformat", "descriptionmarkers", "descriptionmarkersformat", "id", "maxscore", "shortname", "sortorder"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreGradingGetDefinitionsResponseAreasInnerDefinitionsInnerGuideGuideCriteriaInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if descriptionformat (nullable) is None
        # and model_fields_set contains the field
        if self.descriptionformat is None and "descriptionformat" in self.model_fields_set:
            _dict['descriptionformat'] = None

        # set to None if descriptionmarkers (nullable) is None
        # and model_fields_set contains the field
        if self.descriptionmarkers is None and "descriptionmarkers" in self.model_fields_set:
            _dict['descriptionmarkers'] = None

        # set to None if descriptionmarkersformat (nullable) is None
        # and model_fields_set contains the field
        if self.descriptionmarkersformat is None and "descriptionmarkersformat" in self.model_fields_set:
            _dict['descriptionmarkersformat'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if maxscore (nullable) is None
        # and model_fields_set contains the field
        if self.maxscore is None and "maxscore" in self.model_fields_set:
            _dict['maxscore'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['shortname'] = None

        # set to None if sortorder (nullable) is None
        # and model_fields_set contains the field
        if self.sortorder is None and "sortorder" in self.model_fields_set:
            _dict['sortorder'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreGradingGetDefinitionsResponseAreasInnerDefinitionsInnerGuideGuideCriteriaInner from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreGradingGetDefinitionsResponseAreasInnerDefinitionsInnerGuideGuideCriteriaInner" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "description": obj.get("description"),
            "descriptionformat": obj.get("descriptionformat"),
            "descriptionmarkers": obj.get("descriptionmarkers"),
            "descriptionmarkersformat": obj.get("descriptionmarkersformat"),
            "id": obj.get("id"),
            "maxscore": obj.get("maxscore"),
            "shortname": obj.get("shortname"),
            "sortorder": obj.get("sortorder")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


