# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreNotesGetCourseNotesResponseCoursenotesInner(BaseModel):
    """
    CoreNotesGetCourseNotesResponseCoursenotesInner
    """ # noqa: E501
    content: Optional[StrictStr] = Field(description="the content text formated")
    courseid: Optional[StrictInt] = Field(description="id of the course")
    created: Optional[StrictInt] = Field(description="time created (timestamp)")
    format: Optional[StrictInt] = Field(description="content format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)")
    id: Optional[StrictInt] = Field(description="id of this note")
    lastmodified: Optional[StrictInt] = Field(description="time of last modification (timestamp)")
    publishstate: Optional[StrictStr] = Field(description="state of the note (i.e. draft, public, site) ")
    userid: Optional[StrictInt] = Field(description="user id")
    usermodified: Optional[StrictInt] = Field(description="user id of the creator of this note")
    __properties: ClassVar[List[str]] = ["content", "courseid", "created", "format", "id", "lastmodified", "publishstate", "userid", "usermodified"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreNotesGetCourseNotesResponseCoursenotesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict['content'] = None

        # set to None if courseid (nullable) is None
        # and model_fields_set contains the field
        if self.courseid is None and "courseid" in self.model_fields_set:
            _dict['courseid'] = None

        # set to None if created (nullable) is None
        # and model_fields_set contains the field
        if self.created is None and "created" in self.model_fields_set:
            _dict['created'] = None

        # set to None if format (nullable) is None
        # and model_fields_set contains the field
        if self.format is None and "format" in self.model_fields_set:
            _dict['format'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if lastmodified (nullable) is None
        # and model_fields_set contains the field
        if self.lastmodified is None and "lastmodified" in self.model_fields_set:
            _dict['lastmodified'] = None

        # set to None if publishstate (nullable) is None
        # and model_fields_set contains the field
        if self.publishstate is None and "publishstate" in self.model_fields_set:
            _dict['publishstate'] = None

        # set to None if userid (nullable) is None
        # and model_fields_set contains the field
        if self.userid is None and "userid" in self.model_fields_set:
            _dict['userid'] = None

        # set to None if usermodified (nullable) is None
        # and model_fields_set contains the field
        if self.usermodified is None and "usermodified" in self.model_fields_set:
            _dict['usermodified'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreNotesGetCourseNotesResponseCoursenotesInner from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreNotesGetCourseNotesResponseCoursenotesInner" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "content": obj.get("content"),
            "courseid": obj.get("courseid"),
            "created": obj.get("created"),
            "format": obj.get("format"),
            "id": obj.get("id"),
            "lastmodified": obj.get("lastmodified"),
            "publishstate": obj.get("publishstate"),
            "userid": obj.get("userid"),
            "usermodified": obj.get("usermodified")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


