# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from poodle_async_full.models.auth_email_get_signup_settings_response_warnings_inner import AuthEmailGetSignupSettingsResponseWarningsInner
from poodle_async_full.models.core_notes_get_course_notes_response_coursenotes_inner import CoreNotesGetCourseNotesResponseCoursenotesInner
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreNotesGetCourseNotesResponse(BaseModel):
    """
    notes
    """ # noqa: E501
    canmanagecoursenotes: Optional[StrictBool] = Field(default=None, description="Whether the user can manage notes at the given course.")
    canmanagesystemnotes: Optional[StrictBool] = Field(default=None, description="Whether the user can manage notes at system level.")
    coursenotes: Optional[List[CoreNotesGetCourseNotesResponseCoursenotesInner]] = Field(default=None, description="couse notes")
    personalnotes: Optional[List[CoreNotesGetCourseNotesResponseCoursenotesInner]] = Field(default=None, description="personal notes")
    sitenotes: Optional[List[CoreNotesGetCourseNotesResponseCoursenotesInner]] = Field(default=None, description="site notes")
    warnings: Optional[List[AuthEmailGetSignupSettingsResponseWarningsInner]] = Field(default=None, description="list of warnings")
    __properties: ClassVar[List[str]] = ["canmanagecoursenotes", "canmanagesystemnotes", "coursenotes", "personalnotes", "sitenotes", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreNotesGetCourseNotesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in coursenotes (list)
        _items = []
        if self.coursenotes:
            for _item_coursenotes in self.coursenotes:
                if _item_coursenotes:
                    _items.append(_item_coursenotes.to_dict())
            _dict['coursenotes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in personalnotes (list)
        _items = []
        if self.personalnotes:
            for _item_personalnotes in self.personalnotes:
                if _item_personalnotes:
                    _items.append(_item_personalnotes.to_dict())
            _dict['personalnotes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sitenotes (list)
        _items = []
        if self.sitenotes:
            for _item_sitenotes in self.sitenotes:
                if _item_sitenotes:
                    _items.append(_item_sitenotes.to_dict())
            _dict['sitenotes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        # set to None if canmanagecoursenotes (nullable) is None
        # and model_fields_set contains the field
        if self.canmanagecoursenotes is None and "canmanagecoursenotes" in self.model_fields_set:
            _dict['canmanagecoursenotes'] = None

        # set to None if canmanagesystemnotes (nullable) is None
        # and model_fields_set contains the field
        if self.canmanagesystemnotes is None and "canmanagesystemnotes" in self.model_fields_set:
            _dict['canmanagesystemnotes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreNotesGetCourseNotesResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreNotesGetCourseNotesResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "canmanagecoursenotes": obj.get("canmanagecoursenotes"),
            "canmanagesystemnotes": obj.get("canmanagesystemnotes"),
            "coursenotes": [CoreNotesGetCourseNotesResponseCoursenotesInner.from_dict(_item) for _item in obj["coursenotes"]] if obj.get("coursenotes") is not None else None,
            "personalnotes": [CoreNotesGetCourseNotesResponseCoursenotesInner.from_dict(_item) for _item in obj["personalnotes"]] if obj.get("personalnotes") is not None else None,
            "sitenotes": [CoreNotesGetCourseNotesResponseCoursenotesInner.from_dict(_item) for _item in obj["sitenotes"]] if obj.get("sitenotes") is not None else None,
            "warnings": [AuthEmailGetSignupSettingsResponseWarningsInner.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


