# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from poodle_async_full.models.auth_email_get_signup_settings_response_warnings_inner import AuthEmailGetSignupSettingsResponseWarningsInner
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class CoreUserGetPrivateFilesInfoResponse(BaseModel):
    """
    CoreUserGetPrivateFilesInfoResponse
    """ # noqa: E501
    filecount: Optional[StrictInt] = Field(description="Number of files in the area.")
    filesize: Optional[StrictInt] = Field(description="Total size of the files in the area.")
    filesizewithoutreferences: Optional[StrictInt] = Field(description="Total size of the area excluding file references")
    foldercount: Optional[StrictInt] = Field(description="Number of folders in the area.")
    warnings: Optional[List[AuthEmailGetSignupSettingsResponseWarningsInner]] = Field(default=None, description="list of warnings")
    __properties: ClassVar[List[str]] = ["filecount", "filesize", "filesizewithoutreferences", "foldercount", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CoreUserGetPrivateFilesInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        # set to None if filecount (nullable) is None
        # and model_fields_set contains the field
        if self.filecount is None and "filecount" in self.model_fields_set:
            _dict['filecount'] = None

        # set to None if filesize (nullable) is None
        # and model_fields_set contains the field
        if self.filesize is None and "filesize" in self.model_fields_set:
            _dict['filesize'] = None

        # set to None if filesizewithoutreferences (nullable) is None
        # and model_fields_set contains the field
        if self.filesizewithoutreferences is None and "filesizewithoutreferences" in self.model_fields_set:
            _dict['filesizewithoutreferences'] = None

        # set to None if foldercount (nullable) is None
        # and model_fields_set contains the field
        if self.foldercount is None and "foldercount" in self.model_fields_set:
            _dict['foldercount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CoreUserGetPrivateFilesInfoResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "CoreUserGetPrivateFilesInfoResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "filecount": obj.get("filecount"),
            "filesize": obj.get("filesize"),
            "filesizewithoutreferences": obj.get("filesizewithoutreferences"),
            "foldercount": obj.get("foldercount"),
            "warnings": [AuthEmailGetSignupSettingsResponseWarningsInner.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


