# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class EnrolGuestGetInstanceInfoResponseInstanceinfo(BaseModel):
    """
    EnrolGuestGetInstanceInfoResponseInstanceinfo
    """ # noqa: E501
    courseid: Optional[StrictInt] = Field(description="Id of course")
    id: Optional[StrictInt] = Field(description="Id of course enrolment instance")
    name: Optional[StrictStr] = Field(description="Name of enrolment plugin")
    passwordrequired: Optional[StrictBool] = Field(description="Is a password required?")
    status: Optional[StrictBool] = Field(description="Is the enrolment enabled?")
    type: Optional[StrictStr] = Field(description="Type of enrolment plugin")
    __properties: ClassVar[List[str]] = ["courseid", "id", "name", "passwordrequired", "status", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnrolGuestGetInstanceInfoResponseInstanceinfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if courseid (nullable) is None
        # and model_fields_set contains the field
        if self.courseid is None and "courseid" in self.model_fields_set:
            _dict['courseid'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if passwordrequired (nullable) is None
        # and model_fields_set contains the field
        if self.passwordrequired is None and "passwordrequired" in self.model_fields_set:
            _dict['passwordrequired'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnrolGuestGetInstanceInfoResponseInstanceinfo from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "EnrolGuestGetInstanceInfoResponseInstanceinfo" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "courseid": obj.get("courseid"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "passwordrequired": obj.get("passwordrequired"),
            "status": obj.get("status"),
            "type": obj.get("type")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


