# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from poodle_async_full.models.auth_email_get_signup_settings_response_warnings_inner import AuthEmailGetSignupSettingsResponseWarningsInner
from poodle_async_full.models.mod_data_get_entries_response_entries_inner import ModDataGetEntriesResponseEntriesInner
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ModDataSearchEntriesResponse(BaseModel):
    """
    ModDataSearchEntriesResponse
    """ # noqa: E501
    entries: List[ModDataGetEntriesResponseEntriesInner]
    listviewcontents: Optional[StrictStr] = Field(default=None, description="The list view contents as is rendered in the site.")
    maxcount: Optional[StrictInt] = Field(default=None, description="Total count of records that the user could see in the database                     (if all the search criterias were removed).")
    totalcount: Optional[StrictInt] = Field(description="Total count of records returned by the search.")
    warnings: Optional[List[AuthEmailGetSignupSettingsResponseWarningsInner]] = Field(default=None, description="list of warnings")
    __properties: ClassVar[List[str]] = ["entries", "listviewcontents", "maxcount", "totalcount", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModDataSearchEntriesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entries (list)
        _items = []
        if self.entries:
            for _item_entries in self.entries:
                if _item_entries:
                    _items.append(_item_entries.to_dict())
            _dict['entries'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        # set to None if listviewcontents (nullable) is None
        # and model_fields_set contains the field
        if self.listviewcontents is None and "listviewcontents" in self.model_fields_set:
            _dict['listviewcontents'] = None

        # set to None if maxcount (nullable) is None
        # and model_fields_set contains the field
        if self.maxcount is None and "maxcount" in self.model_fields_set:
            _dict['maxcount'] = None

        # set to None if totalcount (nullable) is None
        # and model_fields_set contains the field
        if self.totalcount is None and "totalcount" in self.model_fields_set:
            _dict['totalcount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModDataSearchEntriesResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ModDataSearchEntriesResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "entries": [ModDataGetEntriesResponseEntriesInner.from_dict(_item) for _item in obj["entries"]] if obj.get("entries") is not None else None,
            "listviewcontents": obj.get("listviewcontents"),
            "maxcount": obj.get("maxcount"),
            "totalcount": obj.get("totalcount"),
            "warnings": [AuthEmailGetSignupSettingsResponseWarningsInner.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


