# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ModWikiGetSubwikisResponseSubwikisInner(BaseModel):
    """
    Subwikis
    """ # noqa: E501
    canedit: Optional[StrictBool] = Field(description="True if user can edit the subwiki.")
    groupid: Optional[StrictStr] = Field(description="Group ID.")
    id: Optional[StrictInt] = Field(description="Subwiki ID.")
    userid: Optional[StrictInt] = Field(description="User ID.")
    wikiid: Optional[StrictInt] = Field(description="Wiki ID.")
    __properties: ClassVar[List[str]] = ["canedit", "groupid", "id", "userid", "wikiid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModWikiGetSubwikisResponseSubwikisInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if canedit (nullable) is None
        # and model_fields_set contains the field
        if self.canedit is None and "canedit" in self.model_fields_set:
            _dict['canedit'] = None

        # set to None if groupid (nullable) is None
        # and model_fields_set contains the field
        if self.groupid is None and "groupid" in self.model_fields_set:
            _dict['groupid'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if userid (nullable) is None
        # and model_fields_set contains the field
        if self.userid is None and "userid" in self.model_fields_set:
            _dict['userid'] = None

        # set to None if wikiid (nullable) is None
        # and model_fields_set contains the field
        if self.wikiid is None and "wikiid" in self.model_fields_set:
            _dict['wikiid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModWikiGetSubwikisResponseSubwikisInner from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ModWikiGetSubwikisResponseSubwikisInner" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "canedit": obj.get("canedit"),
            "groupid": obj.get("groupid"),
            "id": obj.get("id"),
            "userid": obj.get("userid"),
            "wikiid": obj.get("wikiid")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


