# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ModLessonGetPagesPossibleJumpsResponseJumpsInner(BaseModel):
    """
    Jump for a page answer
    """ # noqa: E501
    answerid: Optional[StrictInt] = Field(description="The answer id")
    calculatedjump: Optional[StrictInt] = Field(description="The real page id (or EOL) to jump")
    jumpto: Optional[StrictInt] = Field(description="The jump (page id or type of jump)")
    pageid: Optional[StrictInt] = Field(description="The page id")
    __properties: ClassVar[List[str]] = ["answerid", "calculatedjump", "jumpto", "pageid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModLessonGetPagesPossibleJumpsResponseJumpsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if answerid (nullable) is None
        # and model_fields_set contains the field
        if self.answerid is None and "answerid" in self.model_fields_set:
            _dict['answerid'] = None

        # set to None if calculatedjump (nullable) is None
        # and model_fields_set contains the field
        if self.calculatedjump is None and "calculatedjump" in self.model_fields_set:
            _dict['calculatedjump'] = None

        # set to None if jumpto (nullable) is None
        # and model_fields_set contains the field
        if self.jumpto is None and "jumpto" in self.model_fields_set:
            _dict['jumpto'] = None

        # set to None if pageid (nullable) is None
        # and model_fields_set contains the field
        if self.pageid is None and "pageid" in self.model_fields_set:
            _dict['pageid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModLessonGetPagesPossibleJumpsResponseJumpsInner from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ModLessonGetPagesPossibleJumpsResponseJumpsInner" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "answerid": obj.get("answerid"),
            "calculatedjump": obj.get("calculatedjump"),
            "jumpto": obj.get("jumpto"),
            "pageid": obj.get("pageid")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


