# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from poodle_async_full.models.mod_lesson_get_user_attempt_grade_response_grade import ModLessonGetUserAttemptGradeResponseGrade
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ModLessonGetUserAttemptResponseUserstats(BaseModel):
    """
    ModLessonGetUserAttemptResponseUserstats
    """ # noqa: E501
    completed: Optional[StrictInt] = Field(description="Time completed.")
    grade: Optional[Union[StrictFloat, StrictInt]] = Field(description="Attempt final grade.")
    gradeinfo: Optional[ModLessonGetUserAttemptGradeResponseGrade] = None
    timetotake: Optional[StrictInt] = Field(description="Time taken.")
    __properties: ClassVar[List[str]] = ["completed", "grade", "gradeinfo", "timetotake"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModLessonGetUserAttemptResponseUserstats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gradeinfo
        if self.gradeinfo:
            _dict['gradeinfo'] = self.gradeinfo.to_dict()
        # set to None if completed (nullable) is None
        # and model_fields_set contains the field
        if self.completed is None and "completed" in self.model_fields_set:
            _dict['completed'] = None

        # set to None if grade (nullable) is None
        # and model_fields_set contains the field
        if self.grade is None and "grade" in self.model_fields_set:
            _dict['grade'] = None

        # set to None if timetotake (nullable) is None
        # and model_fields_set contains the field
        if self.timetotake is None and "timetotake" in self.model_fields_set:
            _dict['timetotake'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModLessonGetUserAttemptResponseUserstats from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ModLessonGetUserAttemptResponseUserstats" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "completed": obj.get("completed"),
            "grade": obj.get("grade"),
            "gradeinfo": ModLessonGetUserAttemptGradeResponseGrade.from_dict(obj["gradeinfo"]) if obj.get("gradeinfo") is not None else None,
            "timetotake": obj.get("timetotake")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


