# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from poodle_async_full.models.mod_h5pactivity_get_attempts_response_usersattempts_inner_attempts_inner import ModH5pactivityGetAttemptsResponseUsersattemptsInnerAttemptsInner
from poodle_async_full.models.mod_h5pactivity_get_attempts_response_usersattempts_inner_scored import ModH5pactivityGetAttemptsResponseUsersattemptsInnerScored
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ModH5pactivityGetAttemptsResponseUsersattemptsInner(BaseModel):
    """
    ModH5pactivityGetAttemptsResponseUsersattemptsInner
    """ # noqa: E501
    attempts: List[ModH5pactivityGetAttemptsResponseUsersattemptsInnerAttemptsInner] = Field(description="The complete attempts list")
    scored: Optional[ModH5pactivityGetAttemptsResponseUsersattemptsInnerScored] = None
    userid: Optional[StrictInt] = Field(description="The user id")
    __properties: ClassVar[List[str]] = ["attempts", "scored", "userid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModH5pactivityGetAttemptsResponseUsersattemptsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attempts (list)
        _items = []
        if self.attempts:
            for _item_attempts in self.attempts:
                if _item_attempts:
                    _items.append(_item_attempts.to_dict())
            _dict['attempts'] = _items
        # override the default output from pydantic by calling `to_dict()` of scored
        if self.scored:
            _dict['scored'] = self.scored.to_dict()
        # set to None if userid (nullable) is None
        # and model_fields_set contains the field
        if self.userid is None and "userid" in self.model_fields_set:
            _dict['userid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModH5pactivityGetAttemptsResponseUsersattemptsInner from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ModH5pactivityGetAttemptsResponseUsersattemptsInner" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "attempts": [ModH5pactivityGetAttemptsResponseUsersattemptsInnerAttemptsInner.from_dict(_item) for _item in obj["attempts"]] if obj.get("attempts") is not None else None,
            "scored": ModH5pactivityGetAttemptsResponseUsersattemptsInnerScored.from_dict(obj["scored"]) if obj.get("scored") is not None else None,
            "userid": obj.get("userid")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


