# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ModLtiCreateToolTypeResponseState(BaseModel):
    """
    ModLtiCreateToolTypeResponseState
    """ # noqa: E501
    configured: Optional[StrictBool] = Field(description="Is the state configured")
    pending: Optional[StrictBool] = Field(description="Is the state pending")
    rejected: Optional[StrictBool] = Field(description="Is the state rejected")
    text: Optional[StrictStr] = Field(description="Tool type state name string")
    unknown: Optional[StrictBool] = Field(description="Is the state unknown")
    __properties: ClassVar[List[str]] = ["configured", "pending", "rejected", "text", "unknown"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModLtiCreateToolTypeResponseState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if configured (nullable) is None
        # and model_fields_set contains the field
        if self.configured is None and "configured" in self.model_fields_set:
            _dict['configured'] = None

        # set to None if pending (nullable) is None
        # and model_fields_set contains the field
        if self.pending is None and "pending" in self.model_fields_set:
            _dict['pending'] = None

        # set to None if rejected (nullable) is None
        # and model_fields_set contains the field
        if self.rejected is None and "rejected" in self.model_fields_set:
            _dict['rejected'] = None

        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        # set to None if unknown (nullable) is None
        # and model_fields_set contains the field
        if self.unknown is None and "unknown" in self.model_fields_set:
            _dict['unknown'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModLtiCreateToolTypeResponseState from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ModLtiCreateToolTypeResponseState" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "configured": obj.get("configured"),
            "pending": obj.get("pending"),
            "rejected": obj.get("rejected"),
            "text": obj.get("text"),
            "unknown": obj.get("unknown")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


