# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class PaygwPaypalGetConfigForJsResponse(BaseModel):
    """
    PaygwPaypalGetConfigForJsResponse
    """ # noqa: E501
    brandname: Optional[StrictStr] = Field(description="Brand name")
    clientid: Optional[StrictStr] = Field(description="PayPal client ID")
    cost: Optional[Union[StrictFloat, StrictInt]] = Field(description="Cost with gateway surcharge")
    currency: Optional[StrictStr] = Field(description="Currency")
    __properties: ClassVar[List[str]] = ["brandname", "clientid", "cost", "currency"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaygwPaypalGetConfigForJsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if brandname (nullable) is None
        # and model_fields_set contains the field
        if self.brandname is None and "brandname" in self.model_fields_set:
            _dict['brandname'] = None

        # set to None if clientid (nullable) is None
        # and model_fields_set contains the field
        if self.clientid is None and "clientid" in self.model_fields_set:
            _dict['clientid'] = None

        # set to None if cost (nullable) is None
        # and model_fields_set contains the field
        if self.cost is None and "cost" in self.model_fields_set:
            _dict['cost'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaygwPaypalGetConfigForJsResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "PaygwPaypalGetConfigForJsResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "brandname": obj.get("brandname"),
            "clientid": obj.get("clientid"),
            "cost": obj.get("cost"),
            "currency": obj.get("currency")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


