# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class QbankManagecategoriesMoveCategoryResponseInnerFields(BaseModel):
    """
    QbankManagecategoriesMoveCategoryResponseInnerFields
    """ # noqa: E501
    context: Optional[StrictInt] = Field(default=None, description="The ID of the new context.")
    draghandle: Optional[StrictBool] = Field(default=None, description="Should this category have a drag handle?")
    id: Optional[StrictInt] = Field(description="The ID of the category that was updated.")
    parent: Optional[StrictInt] = Field(default=None, description="The ID of the new parent category.")
    sortorder: Optional[StrictInt] = Field(default=None, description="The new sortorder")
    __properties: ClassVar[List[str]] = ["context", "draghandle", "id", "parent", "sortorder"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QbankManagecategoriesMoveCategoryResponseInnerFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if context (nullable) is None
        # and model_fields_set contains the field
        if self.context is None and "context" in self.model_fields_set:
            _dict['context'] = None

        # set to None if draghandle (nullable) is None
        # and model_fields_set contains the field
        if self.draghandle is None and "draghandle" in self.model_fields_set:
            _dict['draghandle'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        # set to None if sortorder (nullable) is None
        # and model_fields_set contains the field
        if self.sortorder is None and "sortorder" in self.model_fields_set:
            _dict['sortorder'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QbankManagecategoriesMoveCategoryResponseInnerFields from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "QbankManagecategoriesMoveCategoryResponseInnerFields" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "context": obj.get("context"),
            "draghandle": obj.get("draghandle"),
            "id": obj.get("id"),
            "parent": obj.get("parent"),
            "sortorder": obj.get("sortorder")
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


