# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from poodle_async_full.models.core_competency_list_competencies_in_template_response_inner import CoreCompetencyListCompetenciesInTemplateResponseInner
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ToolLpDataForTemplateCompetenciesPageResponseStatistics(BaseModel):
    """
    ToolLpDataForTemplateCompetenciesPageResponseStatistics
    """ # noqa: E501
    competencycount: StrictInt = Field(description="competencycount")
    completedplancount: StrictInt = Field(description="completedplancount")
    completedplanpercentage: Union[StrictFloat, StrictInt] = Field(description="completedplanpercentage")
    completedplanpercentageformatted: StrictStr = Field(description="completedplanpercentageformatted")
    leastproficient: List[CoreCompetencyListCompetenciesInTemplateResponseInner] = Field(description="leastproficient")
    leastproficientcount: StrictInt = Field(description="leastproficientcount")
    linkedcompetencycount: StrictInt = Field(description="linkedcompetencycount")
    linkedcompetencypercentage: Union[StrictFloat, StrictInt] = Field(description="linkedcompetencypercentage")
    linkedcompetencypercentageformatted: StrictStr = Field(description="linkedcompetencypercentageformatted")
    plancount: StrictInt = Field(description="plancount")
    proficientusercompetencyplancount: StrictInt = Field(description="proficientusercompetencyplancount")
    proficientusercompetencyplanpercentage: Union[StrictFloat, StrictInt] = Field(description="proficientusercompetencyplanpercentage")
    proficientusercompetencyplanpercentageformatted: StrictStr = Field(description="proficientusercompetencyplanpercentageformatted")
    unlinkedcompetencycount: StrictInt = Field(description="unlinkedcompetencycount")
    usercompetencyplancount: StrictInt = Field(description="usercompetencyplancount")
    __properties: ClassVar[List[str]] = ["competencycount", "completedplancount", "completedplanpercentage", "completedplanpercentageformatted", "leastproficient", "leastproficientcount", "linkedcompetencycount", "linkedcompetencypercentage", "linkedcompetencypercentageformatted", "plancount", "proficientusercompetencyplancount", "proficientusercompetencyplanpercentage", "proficientusercompetencyplanpercentageformatted", "unlinkedcompetencycount", "usercompetencyplancount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolLpDataForTemplateCompetenciesPageResponseStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in leastproficient (list)
        _items = []
        if self.leastproficient:
            for _item_leastproficient in self.leastproficient:
                if _item_leastproficient:
                    _items.append(_item_leastproficient.to_dict())
            _dict['leastproficient'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolLpDataForTemplateCompetenciesPageResponseStatistics from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ToolLpDataForTemplateCompetenciesPageResponseStatistics" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "competencycount": obj.get("competencycount") if obj.get("competencycount") is not None else 0,
            "completedplancount": obj.get("completedplancount") if obj.get("completedplancount") is not None else 0,
            "completedplanpercentage": obj.get("completedplanpercentage") if obj.get("completedplanpercentage") is not None else 0,
            "completedplanpercentageformatted": obj.get("completedplanpercentageformatted") if obj.get("completedplanpercentageformatted") is not None else '',
            "leastproficient": [CoreCompetencyListCompetenciesInTemplateResponseInner.from_dict(_item) for _item in obj["leastproficient"]] if obj.get("leastproficient") is not None else None,
            "leastproficientcount": obj.get("leastproficientcount") if obj.get("leastproficientcount") is not None else 0,
            "linkedcompetencycount": obj.get("linkedcompetencycount") if obj.get("linkedcompetencycount") is not None else 0,
            "linkedcompetencypercentage": obj.get("linkedcompetencypercentage") if obj.get("linkedcompetencypercentage") is not None else 0,
            "linkedcompetencypercentageformatted": obj.get("linkedcompetencypercentageformatted") if obj.get("linkedcompetencypercentageformatted") is not None else '',
            "plancount": obj.get("plancount") if obj.get("plancount") is not None else 0,
            "proficientusercompetencyplancount": obj.get("proficientusercompetencyplancount") if obj.get("proficientusercompetencyplancount") is not None else 0,
            "proficientusercompetencyplanpercentage": obj.get("proficientusercompetencyplanpercentage") if obj.get("proficientusercompetencyplanpercentage") is not None else 0,
            "proficientusercompetencyplanpercentageformatted": obj.get("proficientusercompetencyplanpercentageformatted") if obj.get("proficientusercompetencyplanpercentageformatted") is not None else '',
            "unlinkedcompetencycount": obj.get("unlinkedcompetencycount") if obj.get("unlinkedcompetencycount") is not None else 0,
            "usercompetencyplancount": obj.get("usercompetencyplancount") if obj.get("usercompetencyplancount") is not None else 0
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


