# coding: utf-8

"""
    Moodle Webservice API

    Auto-generated OpenAPI spec for Moodle's Webservice API.

    The version of the OpenAPI document: 4.5.6 (Build: 20250811)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from poodle_async_full.models.core_competency_create_plan_response_template import CoreCompetencyCreatePlanResponseTemplate
from poodle_async_full.models.report_competency_data_for_report_response_usercompetencies_inner_competency import ReportCompetencyDataForReportResponseUsercompetenciesInnerCompetency
from poodle_async_full.models.tool_lp_data_for_template_competencies_page_response_statistics import ToolLpDataForTemplateCompetenciesPageResponseStatistics
from typing import Optional, Set
from typing_extensions import Self

from poodle_async_full.configuration import settings

class ToolLpDataForTemplateCompetenciesPageResponse(BaseModel):
    """
    ToolLpDataForTemplateCompetenciesPageResponse
    """ # noqa: E501
    canmanagecompetencyframeworks: Optional[StrictBool] = Field(description="User can manage competency frameworks")
    canmanagetemplatecompetencies: Optional[StrictBool] = Field(description="User can manage learning plan templates")
    competencies: List[ReportCompetencyDataForReportResponseUsercompetenciesInnerCompetency]
    manageurl: Optional[StrictStr] = Field(description="Url to the manage competencies page.")
    pagecontextid: Optional[StrictInt] = Field(description="Context ID")
    pluginbaseurl: Optional[StrictStr] = Field(description="Base URL of the plugin.")
    statistics: ToolLpDataForTemplateCompetenciesPageResponseStatistics
    template: CoreCompetencyCreatePlanResponseTemplate
    __properties: ClassVar[List[str]] = ["canmanagecompetencyframeworks", "canmanagetemplatecompetencies", "competencies", "manageurl", "pagecontextid", "pluginbaseurl", "statistics", "template"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolLpDataForTemplateCompetenciesPageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in competencies (list)
        _items = []
        if self.competencies:
            for _item_competencies in self.competencies:
                if _item_competencies:
                    _items.append(_item_competencies.to_dict())
            _dict['competencies'] = _items
        # override the default output from pydantic by calling `to_dict()` of statistics
        if self.statistics:
            _dict['statistics'] = self.statistics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        # set to None if canmanagecompetencyframeworks (nullable) is None
        # and model_fields_set contains the field
        if self.canmanagecompetencyframeworks is None and "canmanagecompetencyframeworks" in self.model_fields_set:
            _dict['canmanagecompetencyframeworks'] = None

        # set to None if canmanagetemplatecompetencies (nullable) is None
        # and model_fields_set contains the field
        if self.canmanagetemplatecompetencies is None and "canmanagetemplatecompetencies" in self.model_fields_set:
            _dict['canmanagetemplatecompetencies'] = None

        # set to None if manageurl (nullable) is None
        # and model_fields_set contains the field
        if self.manageurl is None and "manageurl" in self.model_fields_set:
            _dict['manageurl'] = None

        # set to None if pagecontextid (nullable) is None
        # and model_fields_set contains the field
        if self.pagecontextid is None and "pagecontextid" in self.model_fields_set:
            _dict['pagecontextid'] = None

        # set to None if pluginbaseurl (nullable) is None
        # and model_fields_set contains the field
        if self.pluginbaseurl is None and "pluginbaseurl" in self.model_fields_set:
            _dict['pluginbaseurl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolLpDataForTemplateCompetenciesPageResponse from a dict"""
        if obj is None:
            return None

        relaxed = settings.relaxe_all_models or "ToolLpDataForTemplateCompetenciesPageResponse" in settings.relaxed_models

        if not isinstance(obj, dict):
            return cls.model_construct(**obj) if relaxed else cls.model_validate(obj)

        data = {
            "canmanagecompetencyframeworks": obj.get("canmanagecompetencyframeworks"),
            "canmanagetemplatecompetencies": obj.get("canmanagetemplatecompetencies"),
            "competencies": [ReportCompetencyDataForReportResponseUsercompetenciesInnerCompetency.from_dict(_item) for _item in obj["competencies"]] if obj.get("competencies") is not None else None,
            "manageurl": obj.get("manageurl"),
            "pagecontextid": obj.get("pagecontextid"),
            "pluginbaseurl": obj.get("pluginbaseurl"),
            "statistics": ToolLpDataForTemplateCompetenciesPageResponseStatistics.from_dict(obj["statistics"]) if obj.get("statistics") is not None else None,
            "template": CoreCompetencyCreatePlanResponseTemplate.from_dict(obj["template"]) if obj.get("template") is not None else None
        }
        _obj = cls.model_construct(**data) if relaxed else cls.model_validate(data)
        return _obj


