name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: Install dependencies
        run: make install

      - name: Build wheel and source distributions
        run: make build

      - name: Check wheel and source distributions
        run: make check

      - name: Upload to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: make publish
